name: Go

 

on:
  push:
    branches: master
  pull_request:
    branches: master

 

jobs:

 

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

 

    - name: Set up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
#Unit test
    - name: Running unit tests
      run: go test ./hello -v
        
#Removing old binary file   
    - name: Binary remove
      run: |
       rm -r main
       echo "remove binary"
 
#Creating a binary file
    - name: Build
      run: go build main.go
